### ISSUE TITLE
Multi-company support

### ISSUE THREAD

**Issue by codawe** [OCA/credit-control#10]
Is this module ready for a multi-company implementation ? Where customers have different credit for different companies?

**Comment by pedrobaeza** [comment]
Which module?

**Comment by codawe** [comment]
Sorry I don't know how many modules have this project. The functionality I am referring to is the one that lets you put a credit limit on a partner and block sales order if credit is overdue.

**Comment by pedrobaeza** [comment]
Yes, it is then.
