### ISSUE TITLE
send credit control by mail => Emailing Error

### ISSUE THREAD

**Issue by peter2018abc** [OCA/credit-control#11]
Hello

I am trying to send emails using the credit-control module. It creates a message in my outgoing queue that is later being send, so everything would be ok but unfortunately odoo is showing me an "Emailing error":

![grafik](https://user-images.githubusercontent.com/46168043/51841872-e382ea00-230f-11e9-90f5-34be1a426311.png)

Is it somehow possible to send these mails without queuing? Or did I miss something setting this up?

**Comment by peter2018abc** [comment]
Hi!
Am I the only user not being able to use this module du to this Emailing Error?

Thank you for your help

**Comment by pedrobaeza** [comment]
You are not mentioning even the version, but it seems nobody found the same problem.

**Comment by peter2018abc** [comment]
ups, thank you. I am on odoo 11 community, Account Credit Control is 11.0.1.0.1. 

It's so strange. In my case the mails are being qued and send, but the status remains "Emailing Error".
