### ISSUE TITLE
account_credit_control line communication relation

### ISSUE THREAD

**Issue by qgroulard** [OCA/credit-control#116]
Hello,

I am questioning why the link between models 'credit.control.line' and 'credit.control.communication' is O2M since it is possible to execute several actions 'print' or 'send email' on the same 'credit.control.line' which each create a new 'credit.control.communication'.

If a new 'credit.control.communication' is created for a 'credit.control.line' already linked to one, the previous relation will be replaced by a relation between the 'credit.control.line' and the new 'credit.control.communication'.

Other than making old 'credit.control.communication' useless because not linked to any 'credit.control.line' anymore, this may have severer consequences:
When an email (generated from 'credit.control.communication') is sent we search on the communication the 'credit.control.line' in state 'queued' linked to it in order to change their state to 'sent'.
Now imagine that you take a 'credit.control.line', send it by email (which creates a first 'credit.control.communication'), then immediately print the line (which creates a second communication) while the email is queued and not yet actually sent.
Once the email is sent, odoo will look on the first 'credit.control.communication' for linked 'credit.control.line' and won't find any since the 'credit.control.line' is now linked to the second 'credit.control.communication'... Therefore the line will always remain in state 'queued' and never be set to 'sent' even though the email has been sent.

I believe a M2M relation would make more sense and solve this issue, but maybe there is a good reason behind this design choice ?

**Comment by yajo** [comment]
I think some screenshots would help understand you.

The good part is that is was even worse before https://github.com/OCA/credit-control/pull/86, but there I did a small refactor with the main objective of fixing a bug, not to make the module become logic. I agree in that it has a weird design, and its mindset is not easy to follow.

Maybe a deeper refactor should be done when migrating to v14. The module is not easy to understand or use as it is.

**Comment by qgroulard** [comment]
Yes I agree this module needs a deeper refactor.

I have rebuilt runbot for branch 12.0 and configured credit control, you can try what I am describing there.
Here are some screenshot of affected communications nonetheless.

First communication, you can see in the chatter that it has been used to generate the email (if you open the pdf you see it is about the invoice INV/2021/002 for 750$). But no more credit control lines are linked to the communication nor any totals are computed correctly:
![image](https://user-images.githubusercontent.com/43472442/105485125-b4a87000-5cac-11eb-8a2a-461c935f9d14.png)

Second communication (created by printing the same credit control line), everything is set properly. But if I print again the same line, this very communication will be emptied as well....
![image](https://user-images.githubusercontent.com/43472442/105485383-179a0700-5cad-11eb-971e-2bd7edb65307.png)
