### ISSUE TITLE
account_invoice_overdue_reminder: impossible to edit Overdue Invoice Reminder email template

### ISSUE THREAD

**Issue by eLBati** [OCA/credit-control#134]
Versions:

 - [ ] 12.0

Steps:

 - Open Overdue Invoice Reminder email template
 - Make a simple change
 - Save

Email template is messed up

If you run Reminder wizard, it will not work

**Comment by eLBati** [comment]
I tried removing the `object.counter > 2` part (responsible of one of the errors) with this changes
https://gist.github.com/eLBati/156aae2ef9bdacb010b6165e1cdb488a

but other parts are corrupted, for instance the `tr` between
`% for inv in object.invoice_ids.sorted(key='date_invoice'):` and `% endfor` is removed.

Any suggestion?

**Comment by jankowa** [comment]
we have the same problem with odoo14.
Any fix yet?

**Comment by mgielissen** [comment]
A workaround is to edit the translation directly.

**Comment by jankowa** [comment]
> A workaround is to edit the translation directly.

yes, since we not only needed to change the translation, we edited the mail_template.xml inside the module directly. This works so far. 
Any idea what causes the wrong parsing on editing?

**Comment by eLBati** [comment]
I had to remove `html` widget from `body_html` field
