### ISSUE TITLE
Error de validacion

### ISSUE THREAD

**Issue by acastillo456** [OCA/credit-control#189]
## Module
Account Credit Control

## Describe the bug
Las IDs externas no pueden contener espacios

## To Reproduce
**Affected versions**:

1. Download Version 14
2. Install "Account Credit Control"

**Expected behavior**
The module will be installed successfully

**Additional context**
sql constraints exist, the problem is that the name "unique level" must not contain spaces, it must be "unique_level"
![Captura](https://user-images.githubusercontent.com/65291441/167485699-e4c7b217-da32-444f-bd1d-a236f19e482c.PNG)

**Comment by pedrobaeza** [comment]
Fix in #186.
