### ISSUE TITLE
[12.0] account_financial_risk does not load translations correctly

### ISSUE THREAD

**Issue by JuanjoA** [OCA/credit-control#19]
Maybe Odoo12 has  changed the method for load translations, I dont know, but with some changes, the translations load correctly. Tested with _es.po_

Examples:
_ to __ (double)
#: model:ir.model.fields,field_description:account_financial_risk.field_res_partner_move_line_ids
 To
#: model:ir.model.fields,field_description:account_financial_risk.field_res_partner__move_line_ids

Or (model to model_terms)

#: model:ir.ui.view,arch_db:account_financial_risk.account_invoice_confirm_view

To

#: model_terms:ir.ui.view,arch_db:account_financial_risk.account_invoice_confirm_view

Thanks and best regards

**Comment by pedrobaeza** [comment]
Translation comments have changed indeed in v12, but it's handled automatically via PO merge utility. The result is in https://translation.odoo-community.org. Please see there if it's not translated.

**Comment by JuanjoA** [comment]
Thanks Pedro, I will review and post feedback.

**Comment by gdgellatly** [comment]
Probably close this

**Comment by JuanjoA** [comment]
I'm going to check it out right now.
I had missed it, sorry.

**Comment by JuanjoA** [comment]
It's ok, I close.
