### ISSUE TITLE
Error installing the module

### ISSUE THREAD

**Issue by acastillo456** [OCA/credit-control#195]
## Module
account_credit_control

## Describe the bug
malformed translation error

## To Reproduce
version 13.0.2.3.1: The error occurs when installing the module

1. Install the module "account_credit_control"

**Expected behavior**
Perform a complete and correct installation

![Error 2](https://user-images.githubusercontent.com/65291441/174193450-36c249f7-d5e2-4111-b72f-9daefb989982.PNG)
![error 1](https://user-images.githubusercontent.com/65291441/174193459-186e9e01-d952-4fa7-b968-76de6555832d.PNG)

**Comment by pedrobaeza** [comment]
Fixed in 64b60ab0a73a56701cc03ab3ec94686634fdf5d1
