### ISSUE TITLE
account_invoice_overdue_reminder: include the credit notes in the process

### ISSUE THREAD

**Issue by vdewulf** [OCA/credit-control#211]
**Is your feature request related to a problem?**
One of our customers would like to include the credit notes in the process. Here is why. They invoice twice a week all their customers. After delivery of products, they create credit notes. They don't reconcile the credit note with the invoice until the customer pays one of the due invoices and decide to deduct the credit note amount. It's not always 1 invoice - 1 credit note in the way their customer decide to pay. Once the credit note is deducted by the customer from the invoice of his choice, the matching is done in Odoo and the credit note is marked as "paid".

**Describe the solution you'd like**
The account_invoice_overdue_reminder could have an additionnal configuration "do you want to include open credit notes in the reminder process?"
If no => no change to current behavior
If yes => the open credit notes are included in the list of due invoices and in the table in the mail template. In addition, the checkbox "To check if unreconciled payments/refunds above have a good reason not to be reconciled with an open invoice" is not displayed (because not useful, the user would need to always check it manually).

**Describe alternatives you've considered**
Instead of including this credit note feature in the module, we could add it in a separate module.

**Additional context**
We can do the described development and propose it in this repo. Please advise if it can be useful to others and if a separate module would be best or not.
Thanks!
@alexis-via I'd be glad to get your feedback here.
@carmenbianca for follow-up next weeks when I'm off.

**Comment by vdewulf** [comment]
@alexis-via Hello, would you have time to consider our idea/suggestion about credit control module?
Thanks a lot :)

**Comment by vdewulf** [comment]
Discussion during OCA Days 2022 with @alexis-via 

Maybe a new config is not needed. 
We can decide that the process including the credit note can be the new by default behavior of this module.

To be done:
If the credit note is in the process, there is the mail and the screen. On the screen, display the credit note with a line in a different color or different section in the table.

What do you think @legalsylvain and @MiquelRForgeFlow ?

**Comment by legalsylvain** [comment]
:+1:
It makes totally sense. 

And OK to be the default feature.

**Comment by vdewulf** [comment]
@legalsylvain Thanks! 
@MiquelRForgeFlow Any opinion on that? I'll go on with the developement with my dev colleagues next week, I hope.
Thx!

**Comment by MiquelRForgeFlow** [comment]
@vdewulf ok, go on :)

**Comment by carmenbianca** [comment]
Draft PR opened in #226. I suspect I'll get it out of draft state tomorrow.

**Comment by carmenbianca** [comment]
Merged in #226. Issue can be closed
