### ISSUE TITLE
account_invoice_overdue_reminder - requires admin rights to send mail

### ISSUE THREAD

**Issue by PNurm** [OCA/credit-control#219]
## Module
account_invoice_overdue_reminder

## Describe the bug
Cannot send overdue mail unless user has administrator rights

## To Reproduce
**Affected versions**: 14.0

1. Have an overdue invoice
2. Go through the wizard forms
3. 'Validate' will give an error about permissions

**Expected behavior**
Email should be sent, without having administrator level permissions. 

**Additional context**
mail.mail model should be used with sudo() in this context, as it is everywhere else.

**Comment by CasVissers-360ERP** [comment]
@alexis-via I can confirm this bug which makes the module not useable for normal accounting users.

**Comment by CasVissers-360ERP** [comment]
@alexis-via 
This one is a nice one as well, leading to a singleton :) 
```
    def check_warnings(self):
        self.ensure_one()
        for rec in self:
```
The self.ensure_one() can go I think?

**Comment by CasVissers-360ERP** [comment]
@alexis-via 
This issue is still present?
https://watch.screencastify.com/v/zzcp8vTnUro54WT0ReLR
