### ISSUE TITLE
Warning when creating a Quotation

### ISSUE THREAD

**Issue by javimurcia** [OCA/credit-control#26]
Right now, if you install the sale_financial_risk module, you get a warning when you try to confirm a quotatio,n if the client has exceeded the allowable risk (or this sale order would exceed it).

I think it would be nicer to have this warning upfront (as soon you create the quotation) so you don't waste resources trying to close a sale, that has to be renegotiated or has to be dropped completely because the partner has exhausted its credit limit.

A quick solution for this would be to extend the module so the implemented method which is called when a quotation is confirmed (action_confirm) is also called when you press the Send quotation by email (action_quotation_send) or you print the quotation (and print_quotation).

Is there any reason that discourages implementing this behavior?

Maybe, it should be configurable at company level so you can choose when to get the warning (at creation or at confirmation) and maybe, set different permissions, so commercials can ignore the warning when creation the quotation, but the confirmation of the sale has to be done by someone with appropriate permissions.

**Comment by pedrobaeza** [comment]
That depends on your business flow. Other companies may have a long-term quotation planning that covers to create quotation as part of their CRM, or that is very frequent to be in the barrier for being able to be confirmed or not. If you want that behavior, you can add it to the module via a PR, but must be opt-in at company level.

**Comment by gdgellatly** [comment]
The only time a commercial product inventory flow is interested in stop credit in my experience is when confirming a sales order, and if super organized maybe at delivery, I've seen that a few times.

The purpose of these modules is to control financial risk, not stop salespeople wasting time.  A good salesperson is generally aware of their customers credit status and habits anyway.

Quotes -> They don't care. Maybe the account is on stop when they send and off when customer confirms and maybe vice versa, 30 days validity is typical. Moreover, a quote represents zero financial risk so why tie up finance teams. 
 
Invoices -> They don't care. If they've accepted the order and shipped the goods already, there is really no point not charging the customer, or in other words, the invoice also represents zero financial risk, that ship has sailed.  In fact, that functionality required extension to turn off as it is forced by default.

Maybe we can close this.

**Comment by pedrobaeza** [comment]
Yes, closing as there's no PR adding the opt-in mechanism. One affordable thing is to show a ribbon line or similar saying that this will bypass the limit (similar to the outstanding credit/debit in invoices).
