### ISSUE TITLE
credit control queue job

### ISSUE THREAD

**Issue by sbidoul** [OCA/credit-control#32]
Hello,

We need to integrate account_credit_control with queue job to generate a high number of credit control lines, and send a large volume of emails.

Our plan is to add a "Use queue jobs" flag on credit.control.run, so using the feature will be optional.

Is it acceptable / desirable to put this optional feature in the base module (which means a dependency on `queue_job`), or should we refactor the base module to allow for an extension module.

**Comment by pedrobaeza** [comment]
I think it's a heavy dependency. I prefer to be in an extra module.

For the second task, can a more generic approach like `mail_queue_job`  serves? And it's so heavy the first one to need queue?

**Comment by sbidoul** [comment]
Ok, we do an additional module.

And yes it's necessary...

**Comment by pedrobaeza** [comment]
For the refactoring, I suppose that you want to split the work by partner, so an individual method for each partner should be extracted. Then the extra module will overwrite the general one that call the by partner one, and enqueue then instead of calling directly.
