### ISSUE TITLE
[15.0] partner_risk_insurance: Storing computed values of account.move

### ISSUE THREAD

**Issue by JanQubiQ** [OCA/credit-control#365]
Insane storing computed values times of account.move fields

## Module
partner_risk_insurance

## Describe the bug
Since the last improvements on the module, the update is no longer working anymore. I've seen the hook, but it only works on install. These kind of fields are so painful on large databases and shouldn't be deployed on this module maturity.

Is there any way to prevent the calculation once the module is installed?

## To Reproduce
**Version**: 15.0

1. Having partner_risk_insurance module installed, pull the latest changes and update it.

**Comment by JanQubiQ** [comment]
Related PRs: https://github.com/OCA/credit-control/pull/355 https://github.com/OCA/credit-control/pull/359

**Comment by pedrobaeza** [comment]
There's also a migration script for already installed modules.
