### ISSUE TITLE
[17.0] account_financial_risk: The invoice wizard does not open

### ISSUE THREAD

**Issue by pausanchezqubiq** [OCA/credit-control#396]
## Module
account_financial_risk

## Describe the bug
When I try to validate an invoice for a partner with exceeded risk, the wizard that is supposed to warn does not appear. It's confusing because it doesn't confirm the invoice either, so the user can't know what's going on.

## To Reproduce
**v. 17**:

1. Having a customer with exceeded risk (risk_exception = TRUE)
2. Create an invoice for that customer
3. Try to confirm that invoice.

**Expected behavior**
When you try to confirm an invoice for a partner with exceeded risk, it should warn a wizard like it happens in sales.
![image](https://github.com/user-attachments/assets/b26cd16b-27e1-41bc-9059-d017f9e7c2c0)

**Comment by aaladro-kernet** [comment]
Hello,  I am having the same issue

**Comment by carlosdauden** [comment]
I have tested it and it seems to work as expected:
![image](https://github.com/user-attachments/assets/74fd8670-4676-47fe-99ea-7af60ea348ef)

It is possible that you have checked the option that prevents this behaviour?:
![image](https://github.com/user-attachments/assets/953d0c0c-f6c3-4f2c-b04b-72abd7cfec57)

**Comment by aaladro-kernet** [comment]
Yes, is working fine in both the CE and the EE versions.
I have something wrong...
sorry

**Comment by aaladro-kernet** [comment]
Ok, I found out that it is not compatible with account_reports EE, the account_reports module does not return the super result of action_post, this causes, that the invoice is not posted and the wizard does not open.

**Comment by pedrobaeza** [comment]
Then it seems that the enterprise module is the one with the bug. I recommend you to avoid at maximum all the possible enterprise addons.
