### ISSUE TITLE
partner_risk_insurance on Sales

### ISSUE THREAD

**Issue by acsonefho** [OCA/credit-control#50]
We need to manage risk insurance on sale orders.
During the creation of a new sale order, we need to display the amount covered by the insurance (amount covered - total of unpaid (invoices) - total orders not invoiced yet - total of the new current order).
Once the order is validated, this amount must be saved on the SO.

**The question is:**
Should we add this behavior into the existing `partner_risk_insurance` module? Or create a new one?

**Comment by acsonefho** [comment]
@pedrobaeza Can I have your opinion please?

**Comment by pedrobaeza** [comment]
For that you have the *_financial_risk suite (insurance one is only for having the info in the partner, but not linked to flows). And specifically for controlling them on sales you have https://github.com/OCA/credit-control/tree/12.0/sale_financial_risk
