### ISSUE TITLE
[12] Scheduling Credit Control Run and Compute activity

### ISSUE THREAD

**Issue by SSanfilippo** [OCA/credit-control#58]
Hi, I want to schedule the activity for automatize the system of check and notify the customers that hasn't yet payed the invoices.

I try to create one but don't work, I'm not a python developers and I have some difficult to resolve it.

Can anyone help me?

Thanks,
Simone

**Comment by lisandroberardi** [comment]
Hi @SSanfilippo,

Did you find a way to do it? Thanks!

Regards!

**Comment by SSanfilippo** [comment]
Hi @lisandroberardi, no I don't found any solution for that.

**Comment by lisandroberardi** [comment]
> Hi @lisandroberardi, no I don't found any solution for that.

Hi @SSanfilippo ! Thanks anyway! Regards!
