### ISSUE TITLE
[12.0] Is there any credit_limit addon regarding sepa_direct_debit?

### ISSUE THREAD

**Issue by victoralmau** [OCA/credit-control#80]
We have a developed financial risk addon that we have seen should not exist since the **account_credit_control** addon should be used
This addon controls with respect to the field: credit_control and all the payment_mode linked to **sepa_direct_debit** so that before confirming a sale_order it does NOT allow to create it if there is not enough credit (sum of amounts pending invoices with those payment methods and the sum of the amount of the sale_order that you want to confirm).

This addon is the base that we use for another developed regarding: https://www.cesce.es/ (site that allows requesting risk from a client) and for this reason we want to know if we should create that new addon called: **sale_credit_control_sepa_direct_debit**

The addon sale_credit_control_sepa_direct_debit would have account_credit_control as dependency

Later, we would upload another: cesce to https://github.com/OCA/l10n-spain with the dependency of: sale_credit_control_sepa_direct_debit

Is this correct or does something similar already exist or should it be stated differently?

Thank you very much.

**Comment by pedrobaeza** [comment]
This already exists: https://github.com/OCA/credit-control/tree/12.0/sale_financial_risk

**Comment by pedrobaeza** [comment]
For CESCE, it can be interesting to develop an extension module `l10n_es_financial_risk_cesce` that feeds the existing fields.

**Comment by victoralmau** [comment]
Hello, finally, after reviewing everything in detail, I think that using the `partner_risk_insurance` addon https://github.com/OCA/credit-control/tree/12.0 as a base regarding the CESCE addon (with the name that you indicate: `l10n_es_financial_risk_cesce`) would be the most accurate.
I take note about it to change it.

Thank you very much
