### ISSUE TITLE
sale_financial_risk: partner_invoice_id issue

### ISSUE THREAD

**Issue by abirbasolt** [OCA/credit-control#84]
The partner_Invoice_id is who is going to pay, so would be more logical to check the credit from the Partner_invoice_id when you confirm the order.

**Comment by pedrobaeza** [comment]
I told you about opening 2 separate issues. Let's keep this one for the first, so I edited the original text.

**Comment by pedrobaeza** [comment]
@carlosdauden what do you think about this? I think it can be logical to put the risk on the invoicing partner, not the ordering one.

**Comment by carlosdauden** [comment]
I agree

**Comment by pedrobaeza** [comment]
@abirbasolt you can open then a PR solving the problem.

**Comment by carlosdauden** [comment]
Fixed in https://github.com/OCA/credit-control/pull/92

**Comment by pedrobaeza** [comment]
Solved in 13.0, so closing
