### ISSUE TITLE
[RFC] Module account_invoice_overdue_reminder

### ISSUE THREAD

**Issue by Saran440** [OCA/credit-control#87]
From PR : https://github.com/OCA/credit-control/pull/69
@alexis-via 

Hello,
I propose to create new module maybe `base_overdue_reminder` for other module can used reminder (common class and function)
such as my pr: https://github.com/OCA/hr/pull/870 inherited module `account_invoice_overdue_reminder`
and I thought manything can used common.
What do you think or any idea?

Thank you.

**Comment by kittiu** [comment]
@alexis-via I would support the proposal. I think `base_overdue_reminder` can be used more than just invoicing.
I think we can do clean start in v13? (as incubation too).

account_invoice_overdue_reminder to split to,
* account_invoice_overdue_reminder (credit-control)
* base_overdue_reminder (server-ux)

WDYT?
