### ISSUE TITLE
sale_financial_risk: Expected singleton: sale.order()

### ISSUE THREAD

**Issue by BT-aestebanez** [OCA/credit-control#98]
While trying to confirm several orders at once, we face the following issue:

```
def action_confirm
Expected singleton: sale.order(...)
```

Tested on 12.0

**Comment by pedrobaeza** [comment]
Can you add full stack trace?

**Comment by BT-aestebanez** [comment]
Sorry I can't,
but the error is clear:
this function:
https://github.com/OCA/credit-control/blob/348e155a9c6f6e3b322285a685686a941f616bc1/sale_financial_risk/models/sale.py#L36
use self as if it was just an instance (self.ensure_one())
https://github.com/OCA/credit-control/blob/348e155a9c6f6e3b322285a685686a941f616bc1/sale_financial_risk/models/sale.py#L12
but `action_confirm` may be called by several records:
https://github.com/odoo/odoo/blob/f85493a2ef5e13b9d1dedcd8ec7145a4b415c825/addons/sale/models/sale.py#L736

**Comment by pedrobaeza** [comment]
Can you please propose a PR fixing it?

**Comment by BT-aestebanez** [comment]
https://github.com/OCA/credit-control/pull/114
:)
Can you link it to the issue?
